sudo: false 
language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=. manage.py test
after_script:
  - coveralls
